# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: "Terry Zhang"
author: "Terry Zhang"
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I am Terry - A full stack data scientist with a special interest in networks and NLP with experiences in the sustainability sector.
baseurl: "/" # the subpath of the site
url: "https://terryzhang.ca" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "G-WW2XNBPF43"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: iam.terryzhang@gmail.com
      link: mailto:iam.terryzhang@gmail.com
#     - name: WeChat
#       value: YourWeChatUsername
#       link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/theterryzhang
      username: "@theterryzhang"
    - name: LinkedIn
      link: http://linkedin.com/in/zhangterry/
    - name: GitHub
      link: http://github.com/teryakizhang
    - name: Google Scholar
      link: https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AL3_zihltqpFoJ5BQGsk9Zry0CTdXi1EJsUxnML0NXh4PXkXEwlX8z6kFtHMSKofXzeraTwsb5MV_fDX6FRC0A&user=ztrlGNEAAAAJ

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
